server:
  error:
#  include-stacktrace: always
    include-message: always
  port: 8081

spring:
  profiles.active: security
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_security_demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

logging.level:
  org:
    springframework:
      web: DEBUG
      security: DEBUG
