server.error:
#  include-stacktrace: always
  include-message: always

spring:
  profiles.active: security
  datasource:
    url: jdbc:postgresql://localhost:5432/spring_security_demo
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
